import Footer from "@/components/Footer"
import Header from "@/components/Header"
import { ChakraProvider } from "@chakra-ui/react"
import Head from "next/head"

const LayoutRoot = ({ children, metaTitle, metaDescription }) => {
  return (

    <ChakraProvider>
      <Head>
        <title>{`Notes App - ${metaTitle || "Indra Winara"}`}</title>
        <meta
          name="description"
          content={`${metaDescription} || "Generated by create next app"`}
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-between h-screen">
        <div className="w-full flex flex-col">
          <Header />
          {children}
        </div>
        <Footer />
      </div>
    </ChakraProvider >
  )
}



export default LayoutRoot