import Head from 'next/head';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
import Hero from '@/components/Hero';
import Footer from '@/components/Footer';
import SidePanel from '@/components/SidePanel';




const inter = Inter({
  subsets: ['latin'],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>ChatClone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex'>
        <SidePanel />
        <div className='w-full flex flex-col justify-between'>
          <Header />
          <Hero />
          <Footer />
        </div>
      </div>

    </>
  );
}
